# -*- coding: utf-8 -*-
"""Shopping chatbox

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AXlOjlTvqu-z0tDeyjp4XEPH_EtQllw4
"""

print("Hello and welcome to our store")
print("Please enter your name")
name = input()
print("Hi," + name)
print("Please choose the department number you wish to shop in.")
print("1. Grocery")
print("2. Frozen")
print("3. Utencils")
print("4. Clothes")
choice = input()
print("You have chosen" , choice)
print("Thank you")
print("You will be redirected to your disired department.")